#!/bin/sh

# When placed in /etc/network/if-pre-up.d/, this script automatically loads iptables rules on boot.

# --------------------------------------------------#

iptables-restore < /unixme/iptables-rules
