#!/bin/sh

# Compatibility note: This script has only been tested on Debian 7 (wheezy).

# This script should be placed in /etc/network/if-pre-up.d/ so that it automatically
#  runs on boot.

# --------------------------------------------------#

iptables-restore < /etc/iptables.firewall.rules
