#!/bin/bash

# Prints the last 30 lines of the error logs for every enabled Apache site.

# IMPORTANT: The script assumes that all your Apache error logs are
# at /var/www/sitename/error.log.

# SUGGESTION: Save this script to /etc/cron.daily/, and the error logs will be emailed
# to you once a day, assuming you've got MAILTO="your@email.com" in your system
# crontab (/etc/crontab), root user crontab (sudo crontab -e), and non-root user 
# crontab (crontab -u username -e).

# ----------------------------------------------------------------------- #

cd /etc/apache2/sites-enabled

sites=(*)

for site in "${sites[@]}"
do
	echo "Last 30 lines of /var/www/" ${site} "/error.log:"
	tail -n 30 /var/www/${site}/error.log
	printf "\n"
done
