#!/bin/bash

# This script will print last 30 lines of the error logs for every enabled Apache site.
# Your error log files must be stored at /var/www/sitename/error.log.
# Assuming that you've set up your crontab to email you cronjob output,
#  you can save this script in (for example) /etc/cron.daily, and you'll get
#  the recent error logs for your website(s) emailed to you once a day.

# ----------------------------------------------------------------------- #

cd /etc/apache2/sites-enabled

sites=(*)

for site in "${sites[@]}"
do
	echo "Last 30 lines of /var/www/" ${site} "/error.log:"
	tail -n 30 /var/www/${site}/error.log
	printf "\n"
done
